### ISSUE TITLE
[Feature] Ajouter un bouton pour choisir aléatoirement les warriors avant un combat

### ISSUE THREAD

**Issue by Jiiieeef** [ByJC/dbz-figthers#2]
Afin d'éviter les complaintes de tricheries envers Jean-Franck, il faudrait ajouter un bouton qui sélectionne les warriors aléatoirement pour un joueur.

Comme ça il pourra clairement démontrer sa **sainte supériorité** envers ses chers collègues :angel:

**Comment by ByJC** [comment]
Done with : https://github.com/ByJC/dbz-figthers/pull/5
